site_name: "Kfir's Site"
site_url: "https://kfir-g.github.io/"

theme:
  name: material
  logo: assets/logo.jpg
  favicon: assets/logo.jpg
  custom_dir: overrides
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - content.code.copy
    - content.tabs.link
    - content.grid
    - toc.integrate

markdown_extensions:
  # Core
  - admonition
  - attr_list
  - def_list
  - sane_lists
  - smarty
  - md_in_html

  # Pymdown Extensions 
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.extra

plugins:
  - search
  # - rss:
  #     site_url: "https://kfir-g.github.io/"

extra_css:
  - assets/stylesheets/colors.css
  - assets/css/custom.css
  - ./overrides/main.css
